### ISSUE TITLE
Consider moving the VM away from UCC

### ISSUE THREAD

**Issue by gozzarda** [uwapcs/minutes#16]
- Cloud hosting options
- New domain
  - org.au requires an ABN to get, which we can get

**Comment by Tommoa** [comment]
We could just get `.org` instead of `.org.au`. Does that change whether we require an ABN?

**Comment by gozzarda** [comment]
Yes, since the A in ABN standards for the same thing as the au in org.au

I org is more expensive, and it isn't hard for us to get an ABN

**Comment by gozzarda** [comment]
Turns out org.au doesn't actually require an ABN, you just need to phone them up for a chat and then email through the constitution. We now own pcs.org.au.

**Comment by gozzarda** [comment]
We have moved the VM to DigitalOcean, the club gmail has access to it, and the new domain points to it.
