### ISSUE TITLE
Organise Introduction to Programming Event

### ISSUE THREAD

**Issue by pritchardn** [uwapcs/minutes#49]
Nic - All the admin things
Gozz - All the content things

**Comment by gozzarda** [comment]
First session is going to be titled:
introduction_to_programming[0] = "What is a Computer, Anyway?"

Somewhat concerned about people thinking session 0 is unimportant and session 1 is the first.

Will be covering the formalization of the concept of the computer.

This will likely include lambda calculus and Turing machines, at least to stay with.
