### ISSUE TITLE
Tech Talk Ideas

### ISSUE THREAD

**Issue by pritchardn** [uwapcs/minutes#58]
In preparation for the end of the formal Introduction to Programming series, it'd be nice to keep the events going with useful/interesting topics of interest

**Comment by pritchardn** [comment]
Some ideas of my own:
  - Intro to Linux 
  - Quantum Computing: why it scares me but shouldn't scare you
  - Obligatory JS rant

**Comment by gozzarda** [comment]
The previously discussed I've that I think super valuable is Git and GitHub.

Maybe also an introduction to Linux for development. Getting them access to a machine to use is hard though.

**Comment by pritchardn** [comment]
Closed since relevant discussion should be moved to #71 and #68
