### ISSUE TITLE
Social Event

### ISSUE THREAD

**Issue by pritchardn** [uwapcs/minutes#61]
As per minutes in #60 we could possibly run a social event in one of the final training sessions
  - [ ] Date
  - [ ] Idea 
  - [ ] Room Booking
  - [ ] EMP
  - [ ] Banner / Promotional Material

**Comment by pritchardn** [comment]
Deferred until next semester (do it once, do it properly)

**Comment by Dadams2** [comment]
Ice skating
Cockburn ice areana will do $17 for a group of 15 or more
Mirabooka (extreme ice areana) will do a family pass for 4 people for $50 will need to check.
