### ISSUE TITLE
Agree on 2019-S2 Shirt Design

### ISSUE THREAD

**Issue by pritchardn** [uwapcs/minutes#77]
If we're happy with the grey that's fine but it might be nice to consider some other options

**Comment by gozzarda** [comment]
I am personally of the mind that we should stick with the full-colour logo on heather that we did last year. Main thing is getting them to members. Biggest thing is going to be whether we offer full-chest logos, small logos on one breast, or a choice.

**Comment by pritchardn** [comment]
Shirt form is in the Google drive under Odd Ends
