### ISSUE TITLE
Room bookings for IntrotoProgramming

### ISSUE THREAD

**Issue by pritchardn** [uwapcs/minutes#80]
Book room 1.24 4pm-6pm any night of the week (except Friday)
Weeks 2-12 (5/8 -> 21/10)

**Comment by Dadams2** [comment]
I have not specifically requested this booking yet as i think we should wait untill timetables are done and work out when the first and second year labs are on, then not hold training during those times.

**Comment by Dadams2** [comment]
request has been sent

**Comment by Dadams2** [comment]
room has been booked every week of semester tuesday and wednesday from 4-6pm and booking has been confirmed
