### ISSUE TITLE
Create a better title than 'Intro to Computer Science/Programming'

### ISSUE THREAD

**Issue by pritchardn** [uwapcs/minutes#81]

**Comment by gozzarda** [comment]
My current best plan is to do the sneaky thing of marketting the same thing three times:
- The overall course is called "CSSE stuff we wish we had known sooner"
- The first 3-ish sessions are "Introduction to Programming"
- The very first session is "Computers: How do they work?"

All titles are just thematic examples at this point and open to suggestions.

The point here is that while **we** know, frankly, better than our students what we should be covering first. We therefore need to convince people that they should come to the first session so we can tell them what the course plan is and why they should stick around. We end up with three groups we want to catch:
- Those who have no idea about anything computer related and need something that sounds accessible and low-commitment (1 session about "how computers work")
- Those who know they want to learn to program (we should explicitly also mention that this is good for people who already know how to program), this is IntroProg
- Those that think they already know how to program but likely have patchy understanding of some things who we want to rope in for the whole course to cover everything they don't understand properly
  - This must be title in such a way that everyone from first years to graduates feel they can and should attend

Feedback is much appreciated. Titles can be made to sound much better, I think, but that is the meaning behind them.
