### ISSUE TITLE
Practical Programming

### ISSUE THREAD

**Issue by pritchardn** [uwapcs/minutes#86]
The refinement of previous course.
Possible additions include a programming paradigms component

**Comment by gozzarda** [comment]
Just had a look through the three sessions we ran last year, and the first two look fine.

I have decided to change up the third session though, as we currently use Hello World as the first example program for tradition reasons, and it is bad, so we shouldn't.

A fourth session on programming paradigms is probably very much worthwhile. Should cover:
- Imperative vs Declarative
- Object Oriented Programming (that is, what we call OOP nowadays)
- Message Oriented Programming (what OOP actually is, before it got corrupted)
- Functional Programming

Having then covered OOP would be useful if we want to do a Python or C++ course.
